apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: motus

resources:
  - namespace.yaml
  - runtime-config.yaml
  - app-secrets.yaml
  - postgres-init-configmap.yaml
  - postgres.yaml
  - redis.yaml
  - web.yaml
  - game.yaml
  - ingress.yaml
  - pdb.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: motus-royale
      app.kubernetes.io/part-of: motus-royale
