apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web
  labels:
    app.kubernetes.io/component: web
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: web
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: game
  labels:
    app.kubernetes.io/component: game
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: game
